Ромашкина Мария: Б05-332 : контест 2 : задача K
rorororom/LabAlgo_2 pull request #5
Opened 2024-10-14 12:18 UTC by rorororom

2024-10-15 20:54 UTC, VTroyanGolovyan requested changes
https://google.github.io/styleguide/cppguide.html
Нейминг

2024-10-28 06:43 UTC, aksden42 commented
Проблема нейминга всё еще актуальна

2024-10-28 06:44 UTC, aksden42 commented
size_t

2024-10-28 06:46 UTC, aksden42 commented on contest2_task_K/contest2_task_K.cpp
> +  std::vector<std::vector<long long>> dp(numLines + 1, std::vector<long long>(numSegments + 1, kInf));
что такое dp?

2024-10-28 06:46 UTC, aksden42 commented on contest2_task_K/contest2_task_K.cpp
> +int main() {
много кода в main, декомпозируй

2024-10-28 06:46 UTC, aksden42 commented on contest2_task_K/contest2_task_K.cpp
> +  std::cout << dp[numLines][numSegments] << std::endl;
\n

2024-10-28 06:46 UTC, aksden42 commented on contest2_task_K/contest2_task_K.cpp
> +  }
хочется это вынести во что-то отдельное

2024-10-28 06:48 UTC, aksden42 commented on contest2_task_K/contest2_task_K.cpp
> +class Line {
класс и без приватных полей, наверное это структура. Сделай поля приватными

2024-10-28 06:48 UTC, aksden42 commented on contest2_task_K/contest2_task_K.cpp
> +class ConvexHullTrick {
у тебя тут всё публичное, сделай поля приватными

2024-11-06 07:36 UTC, merged